#!/usr/bin/env python3
"""Keep the layer-dependency table of docs/dev/architecture.md derived from code.

``architecture_principles.md`` §4 states that mechanical structure is maintained
by a generator rather than drawn by hand, and names architecture.md §2.1's text
dependency table as exactly that kind of structure.  Until this script existed
that table was hand-written, and it had drifted -- five classes of edges were
missing or contradicted (see the stage-4 audit row in the same §5 table).

The block between the BEGIN/END markers is a pure function of the source tree:
every layer-to-layer edge is measured with ``ast``, so the table cannot record
anything the code does not do.  ``--check`` fails when the document differs from
what the code says.

Facts live in the block; judgement does not.  Which reverse edges have been
ruled acceptable, and why, is policy: it is written in the hand-written prose
*outside* the markers, where a reviewer can see it change.

Coverage boundary, stated rather than implied: this block covers **layer-to-layer**
edges only.  Edges *within* a layer, and import cycles, are not generated here --
they are corrected in prose and re-checked by hand.

Excluded from the measurement: the package facade (``pu_toolbox/__init__.py``)
and the top-level helper modules (``pu_toolbox/progress.py``,
``pu_toolbox/run_config.py``).  They belong to no layer; the facade is an
umbrella re-export that legitimately reaches every layer, so including it would
drown the real edges.

Coverage boundary of ``validate_layout``: it checks the directories holding
``.py`` files *inside* ``pu_toolbox/`` -- regular packages and namespace-style
directories alike -- against the layer map.  A top-level root outside the package is
only covered when the map lists it (``benchmarks/`` is listed as part of the
User Layer); adding a new sibling root means adding it to ``LAYERS`` by hand.
A whitelist of top-level directories would just be one more hand-maintained
record to drift, which is the failure this batch exists to remove.

Usage::

    uv run python scripts/generate_layer_deps.py --check    # verify (exit 0/1)
    uv run python scripts/generate_layer_deps.py --update   # rewrite the block
"""

from __future__ import annotations

import argparse
import ast
import sys
from collections.abc import Mapping
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ARCHITECTURE_MD = PROJECT_ROOT / "docs" / "dev" / "architecture.md"

BEGIN_MARK = (
    "<!-- BEGIN: layer-deps (generated by scripts/generate_layer_deps.py; do not edit by hand) -->"
)
END_MARK = "<!-- END: layer-deps -->"

# Layer name -> the top-level roots that make it up, relative to the repository
# root.  The key order is the layer order used when rendering, and it follows
# architecture.md §2.  ``benchmarks/`` is a top-level package outside
# ``pu_toolbox/``, which is why roots are spelled out in full.
LAYERS: dict[str, tuple[str, ...]] = {
    "Core": (
        "pu_toolbox/core",
        "pu_toolbox/preprocessing",
        "pu_toolbox/registry",
        "pu_toolbox/advisor",
        "pu_toolbox/utils",
    ),
    "Estimation": ("pu_toolbox/prior", "pu_toolbox/losses"),
    "Algorithms": ("pu_toolbox/estimators",),
    "Evaluation": (
        "pu_toolbox/metrics",
        "pu_toolbox/model_selection",
        "pu_toolbox/diagnostics",
    ),
    "Orchestration": ("pu_toolbox/workflows", "pu_toolbox/cli"),
    "Experiment": ("pu_toolbox/experiment",),
    "User Layer": ("pu_toolbox/ui", "benchmarks"),
}

_SKIP_PARTS = {"__pycache__"}


def _module_name(path: Path, root: Path) -> str:
    """Dotted module name of a file, with *root* as the package root.

    Both ``pu_toolbox/`` and ``benchmarks/`` are top-level packages of this
    repository, so the repository root is the package root for every file this
    script measures -- one rule, no per-layer special case.
    """
    parts = list(path.relative_to(root).with_suffix("").parts)
    if parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def _package_of(path: Path, root: Path) -> str:
    """Dotted package **containing** *path*; the module itself is not included.

    Relative imports resolve against this, so it must stop one level short of
    the file.  ``__init__.py`` is the exception: its own package *is* the module
    name ``_module_name`` returns.
    """
    module = _module_name(path, root)
    if path.name == "__init__.py":
        return module
    return module.rsplit(".", 1)[0]


def _from_candidates(node: ast.ImportFrom, package: str) -> list[str]:
    """Dotted names an ``ImportFrom`` can bind.

    ``from X import a`` may import the submodule ``X.a``, so each alias is a
    candidate too -- that is what catches ``from pkg import low``.
    """
    if node.level:
        parts = package.split(".")
        depth = len(parts) - (node.level - 1)
        if depth < 0:
            # Deeper than the package root: a fatal ImportError at runtime,
            # which imports nothing.  A negative slice would wrap around and
            # synthesise a hit.
            return []
        anchor = ".".join([*parts[:depth], node.module]) if node.module else ".".join(parts[:depth])
    else:
        anchor = node.module or ""
    if not anchor:
        return []
    return [anchor, *(f"{anchor}.{alias.name}" for alias in node.names)]


class _Collector(ast.NodeVisitor):
    """Collect import targets, split by whether they sit inside a function."""

    def __init__(self, package: str) -> None:
        self.package = package
        self.module_level: list[str] = []
        self.function_local: list[str] = []
        self._depth = 0

    def _visit_function(self, node: ast.AST) -> None:
        self._depth += 1
        self.generic_visit(node)
        self._depth -= 1

    visit_FunctionDef = _visit_function  # noqa: N815 (ast.NodeVisitor dispatch name)
    visit_AsyncFunctionDef = _visit_function  # noqa: N815 (ast.NodeVisitor dispatch name)

    def visit_Import(self, node: ast.Import) -> None:
        self._record([alias.name for alias in node.names])

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:
        self._record(_from_candidates(node, self.package))

    def _record(self, candidates: list[str]) -> None:
        bucket = self.function_local if self._depth else self.module_level
        bucket.extend(candidates)


def _layer_of(dotted: str, layers: Mapping[str, tuple[str, ...]]) -> str | None:
    """Layer owning a dotted module name, or None when it belongs to no layer."""
    for layer, roots in layers.items():
        for root in roots:
            prefix = root.replace("/", ".")
            if dotted == prefix or dotted.startswith(prefix + "."):
                return layer
    return None


def _layer_sources(root: Path, layers: Mapping[str, tuple[str, ...]]) -> list[tuple[str, Path]]:
    """Every ``.py`` file of every layer, sorted for reproducibility."""
    out: list[tuple[str, Path]] = []
    for layer, roots in layers.items():
        for rel_root in roots:
            base = root / rel_root
            if not base.is_dir():
                continue
            for path in sorted(base.rglob("*.py")):
                if _SKIP_PARTS & set(path.parts):
                    continue
                out.append((layer, path))
    return sorted(out, key=lambda item: str(item[1]))


PACKAGE_NAME = "pu_toolbox"


def validate_layout(
    root: Path = PROJECT_ROOT,
    layers: Mapping[str, tuple[str, ...]] = LAYERS,
) -> None:
    """Fail loudly when the layer map no longer describes the package tree.

    Two ways the map can go stale, both of which would otherwise drop edges
    from the generated table with no trace in the output:

    * a declared root no longer exists (a rename, a typo, a deleted package);
    * a directory exists under ``pu_toolbox/`` that no layer lists -- such a
      directory is invisible both as a source and as an edge target, because
      ``_layer_of`` only matches declared prefixes.  What is checked is any
      directory holding ``.py`` files, not only a regular package: a
      namespace-style directory (no ``__init__.py``) hides edges just as well.

    A generator that quietly reports "everything is fine" is worse than one
    that stops, so both cases raise.
    """
    missing = sorted(rel for roots in layers.values() for rel in roots if not (root / rel).is_dir())
    if missing:
        raise ValueError(f"declared layer roots do not exist: {missing}")

    package = root / PACKAGE_NAME
    if not package.is_dir():
        return
    covered = [rel for roots in layers.values() for rel in roots]
    # A set, not a list: the walk yields one entry per ``.py`` file, so a
    # directory holding several files would otherwise be reported once per file.
    unlisted = sorted(
        {
            rel
            for source in package.rglob("*.py")
            if (rel := source.parent.relative_to(root).as_posix()) != PACKAGE_NAME
            and not any(rel == entry or rel.startswith(entry + "/") for entry in covered)
        }
    )
    if unlisted:
        raise ValueError(
            f"directories under {PACKAGE_NAME}/ that no layer lists, so their .py "
            f"files would be dropped silently: {unlisted}"
        )


def measure_edges(
    root: Path = PROJECT_ROOT,
    layers: Mapping[str, tuple[str, ...]] = LAYERS,
) -> dict[str, dict[str, str]]:
    """Layer-to-layer edges measured from the source tree.

    Returns ``{source_layer: {target_layer: "module" | "function"}}``.  The
    value is ``"function"`` when the edge exists *only* through imports inside
    function bodies -- such edges are invisible to an import graph, so the
    distinction is recorded rather than flattened away.

    A file that cannot be parsed raises rather than being skipped: silently
    dropping its edges would under-report, which is the failure mode this whole
    script exists to remove.

    Raises ``ValueError`` when the layer map no longer matches the tree on
    disk -- see ``validate_layout``.  That check runs *inside* this function,
    not in ``main``, so a caller who invokes ``measure_edges`` directly still
    gets the loud failure instead of a silently under-reported result.
    """
    validate_layout(root, layers)
    edges: dict[str, dict[str, str]] = {}
    for source_layer, path in _layer_sources(root, layers):
        package = _package_of(path, root)
        source = path.read_text(encoding="utf-8")
        collector = _Collector(package)
        collector.visit(ast.parse(source, filename=str(path)))

        found: dict[str, str] = {}
        for candidates, kind in (
            (collector.module_level, "module"),
            (collector.function_local, "function"),
        ):
            for dotted in candidates:
                target = _layer_of(dotted, layers)
                if target is None or target == source_layer:
                    continue
                if found.get(target) != "module":
                    found[target] = kind
        if found:
            # Merge, never replace: a layer is many files, and assigning here
            # would let the last file scanned overwrite every earlier one's
            # edges.  "module" wins over "function" when either file shows the
            # import at module level.
            bucket = edges.setdefault(source_layer, {})
            for target, kind in found.items():
                if bucket.get(target) != "module":
                    bucket[target] = kind
    return edges


def _display(layer: str, layers: Mapping[str, tuple[str, ...]]) -> str:
    roots = "、".join(f"`{Path(r).name}/`" for r in layers[layer])
    return f"{layer}（{roots}）"


def _targets(
    edges: Mapping[str, Mapping[str, str]], layer: str, layers: Mapping[str, tuple[str, ...]]
) -> str:
    row = edges.get(layer)
    if not row:
        return "—"
    order = list(layers)
    parts = []
    for target in sorted(row, key=order.index):
        suffix = "（仅函数内）" if row[target] == "function" else ""
        parts.append(f"{target}{suffix}")
    return "、".join(parts)


def render_block(
    edges: Mapping[str, Mapping[str, str]],
    layers: Mapping[str, tuple[str, ...]] = LAYERS,
    newline: str = "\n",
) -> str:
    """Render the generated markdown block, markers included."""
    lines = [
        BEGIN_MARK,
        "**层间调用方向**（指向被依赖方；由代码实测生成，勿手改）：",
        "",
        "| 层 | 使用/调用 |",
        "|---|---|",
    ]
    lines.extend(
        f"| {_display(layer, layers)} | {_targets(edges, layer, layers)} |" for layer in layers
    )
    lines.append(END_MARK)
    return newline.join(lines) + newline


def replace_block(text: str, block: str) -> str:
    """Swap the marked block in *text* for *block*.

    Raises ``ValueError`` when the markers are absent or out of order -- a
    silently un-replaced document is exactly the drift this guards against.
    """
    start = text.find(BEGIN_MARK)
    end = text.find(END_MARK)
    if start < 0 or end < 0 or end < start:
        raise ValueError(f"markers not found in order: {BEGIN_MARK!r} .. {END_MARK!r}")
    end += len(END_MARK)
    # Trailing newline of the old block belongs to the block, not the document.
    if text[end : end + 2] == "\r\n":
        end += 2
    elif text[end : end + 1] == "\n":
        end += 1
    return text[:start] + block + text[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate the architecture.md layer-dependency block."
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--check", action="store_true", help="verify the document matches the code (default)"
    )
    group.add_argument("--update", action="store_true", help="rewrite the generated block")
    args = parser.parse_args(argv)

    # ``newline=""`` on both ends: the file's own line endings are preserved
    # instead of being rewritten to the platform default.  architecture.md is
    # stored LF in git and checked out CRLF on Windows, so hardcoding either
    # would produce a false failure on the other platform.
    with ARCHITECTURE_MD.open(encoding="utf-8", newline="") as handle:
        text = handle.read()
    newline = "\r\n" if "\r\n" in text else "\n"

    try:
        # Pass the module globals explicitly: a default argument is bound once,
        # at definition time, so a bare ``measure_edges()`` would keep the layer
        # map this module was imported with and silently ignore any override.
        block = render_block(
            measure_edges(root=PROJECT_ROOT, layers=LAYERS),
            layers=LAYERS,
            newline=newline,
        )
    except (SyntaxError, ValueError) as exc:
        print(f"cannot measure layer edges: {exc}")
        return 1

    try:
        new_text = replace_block(text, block)
    except ValueError as exc:
        print(str(exc))
        return 1

    if args.update:
        if new_text != text:
            with ARCHITECTURE_MD.open("w", encoding="utf-8", newline="") as handle:
                handle.write(new_text)
            print(f"updated {ARCHITECTURE_MD.relative_to(PROJECT_ROOT)}")
        else:
            print("layer-deps block already up to date")
        return 0

    if new_text != text:
        print(
            "architecture.md §2.1 layer-deps block is stale -- "
            "run `uv run python scripts/generate_layer_deps.py --update`"
        )
        return 1
    print("layer-deps block is up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
